-- 🗄️ DATABASE MIGRATIONS
-- Run these SQL commands to add new columns for the fixed system

-- ==========================================
-- ✅ MIGRATION 1: Add officer contact & location
-- ==========================================
-- Adds contact number and jurisdiction location to police officers

ALTER TABLE police_officers 
ADD COLUMN contact VARCHAR(20);

ALTER TABLE police_officers 
ADD COLUMN location VARCHAR(255);

-- Example: Update test officer
UPDATE police_officers 
SET contact = '9876543210', 
    location = 'Dongri, Mumbai' 
WHERE officer_id = 1;


-- ==========================================
-- ✅ MIGRATION 2: Add generated FIR storage
-- ==========================================
-- Stores the formal FIR text generated by LLM

ALTER TABLE firs 
ADD COLUMN generated_fir TEXT;

-- Add creation timestamp
ALTER TABLE firs 
ADD COLUMN created_at DATE;

-- Set default for existing records
UPDATE firs 
SET created_at = CURRENT_DATE 
WHERE created_at IS NULL;


-- ==========================================
-- ✅ MIGRATION 3: Verify AIAnalysis columns
-- ==========================================
-- These should already exist, but verify

-- Should have:
-- - missing_information TEXT
-- - suggestions TEXT
-- - confidence_score FLOAT

-- If missing, run:
-- ALTER TABLE ai_analysis ADD COLUMN missing_information TEXT;
-- ALTER TABLE ai_analysis ADD COLUMN suggestions TEXT;
-- ALTER TABLE ai_analysis ADD COLUMN confidence_score FLOAT;


-- ==========================================
-- ✅ MIGRATION 4: Add test data (OPTIONAL)
-- ==========================================
-- Add sample police station and officer for testing

-- Add police station if not exists
INSERT INTO police_stations (station_name, location, contact_number)
SELECT 'Mumbai Central Police Station', 'Dongri, Mumbai', '02212345678'
WHERE NOT EXISTS (
  SELECT 1 FROM police_stations WHERE station_name = 'Mumbai Central Police Station'
);

-- Get station ID for the next insert
-- SELECT station_id FROM police_stations WHERE station_name = 'Mumbai Central Police Station';

-- Add test officer (replace station_id with actual value from above)
INSERT INTO police_officers (name, email, password, rank, contact, location, station_id)
SELECT 
  'Rajesh Kumar',
  'rajesh.kumar@police.gov',
  'hashed_password_here',
  'Sub-Inspector',
  '9876543210',
  'Dongri, Mumbai',
  (SELECT station_id FROM police_stations WHERE station_name = 'Mumbai Central Police Station' LIMIT 1)
WHERE NOT EXISTS (
  SELECT 1 FROM police_officers WHERE name = 'Rajesh Kumar'
);


-- ==========================================
-- ✅ VERIFICATION QUERIES
-- ==========================================
-- Run these to verify migrations were successful

-- Check police_officers has new columns
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'police_officers' 
ORDER BY ordinal_position;

-- Check firs has new columns
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'firs' 
ORDER BY ordinal_position;

-- Check ai_analysis has all required columns
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'ai_analysis' 
ORDER BY ordinal_position;

-- Check if test officer exists
SELECT officer_id, name, rank, contact, location, station_id 
FROM police_officers 
LIMIT 5;

-- Check if test station exists
SELECT station_id, station_name, location, contact_number 
FROM police_stations 
LIMIT 5;


-- ==========================================
-- ✅ QUICK TEST QUERIES
-- ==========================================
-- Run after migrations to verify everything works

-- Get all officers with their stations
SELECT 
  po.officer_id,
  po.name,
  po.rank,
  po.contact,
  po.location,
  ps.station_name,
  ps.location as station_location
FROM police_officers po
LEFT JOIN police_stations ps ON po.station_id = ps.station_id;

-- Get all FIRs with generated text
SELECT 
  fir_id,
  description,
  generated_fir,
  status,
  created_at
FROM firs 
ORDER BY created_at DESC 
LIMIT 5;

-- Get all AI analyses
SELECT 
  analysis_id,
  fir_id,
  missing_information,
  suggestions,
  confidence_score,
  analysis_date
FROM ai_analysis 
ORDER BY analysis_date DESC 
LIMIT 5;




-- ✅ CHAT HISTORY TABLE
CREATE TABLE IF NOT EXISTS chat_history (
    chat_id SERIAL PRIMARY KEY,
    fir_id INT,
    message TEXT,
    role VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);