import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    appName: 'FIR Sahayak',
    loginTitle: 'Police Station Login',
    stationName: 'Station Name',
    stationLocation: 'Station Location',
    contactNumber: 'Contact Number',
    next: 'Next',
    officerLogin: 'Officer Login',
    officerName: 'Officer Name',
    emailId: 'Email ID',
    password: 'Password',
    login: 'Login',
    newChat: 'New Chat',
    history: 'History',
    noChats: 'No saved chats yet',
    inputPlaceholder: 'Describe the incident in simple language...',
    solveCase: 'How to solve this case',
    downloadFIR: 'Download FIR Format',
    checkMissing: 'Check Missing Information',
    findJurisdiction: 'Find Police Jurisdiction',
    knowRights: 'Know Your Rights',
    incidentSummary: 'Incident Summary',
    legalSteps: 'Legal Steps',
    missingDetails: 'Missing Details',
  },
  hi: {
    appName: 'एफआईआर सहायक',
    loginTitle: 'पुलिस स्टेशन लॉगिन',
    stationName: 'स्टेशन का नाम',
    stationLocation: 'स्टेशन का स्थान',
    contactNumber: 'संपर्क नंबर',
    next: 'आगे बढ़ें',
    officerLogin: 'अधिकारी लॉगिन',
    officerName: 'अधिकारी का नाम',
    emailId: 'ईमेल आईडी',
    password: 'पासवर्ड',
    login: 'लॉगिन',
    newChat: 'नई चैट',
    history: 'इतिहास',
    noChats: 'अभी तक कोई चैट सहेजी नहीं गई है',
    inputPlaceholder: 'घटना का सरल भाषा में वर्णन करें...',
    solveCase: 'इस मामले को कैसे हल करें',
    downloadFIR: 'एफआईआर प्रारूप डाउनलोड करें',
    checkMissing: 'लापता जानकारी की जाँच करें',
    findJurisdiction: 'पुलिस क्षेत्राधिकार खोजें',
    knowRights: 'अपने अधिकार जानें',
    incidentSummary: 'घटना का सारांश',
    legalSteps: 'कानूनी कदम',
    missingDetails: 'लापता विवरण',
  },
  mr: {
    appName: 'एफआयआर सहाय्यक',
    loginTitle: 'पोलीस स्टेशन लॉगिन',
    stationName: 'स्टेशनचे नाव',
    stationLocation: 'स्टेशनचे ठिकाण',
    contactNumber: 'संपर्क क्रमांक',
    next: 'पुढील',
    officerLogin: 'अधिकारी लॉगिन',
    officerName: 'अधिकाऱ्याचे नाव',
    emailId: 'ईमेल आयडी',
    password: 'पासवर्ड',
    login: 'लॉगिन',
    newChat: 'नवीन चॅट',
    history: 'इतिहास',
    noChats: 'अद्याप कोणतीही चॅट जतन केलेली नाही',
    inputPlaceholder: 'घटनेचे सोप्या भाषेत वर्णन करा...',
    solveCase: 'हे प्रकरण कसे सोडवायचे',
    downloadFIR: 'एफआयआर फॉरमॅट डाउनलोड करा',
    checkMissing: 'गहाळ माहिती तपासा',
    findJurisdiction: 'पोलीस अधिकार क्षेत्र शोधा',
    knowRights: 'तुमचे अधिकार जाणून घ्या',
    incidentSummary: 'घटनेचा सारांश',
    legalSteps: 'कायदेशीर पावले',
    missingDetails: 'गहाळ तपशील',
  }
};
