from sqlalchemy import Column, Integer, String, Text, Date, DateTime, ForeignKey, Float
from datetime import datetime
from sqlalchemy.orm import relationship
from backend.db.database import Base
from pgvector.sqlalchemy import Vector   # ADD THIS



class PoliceStation(Base):
    __tablename__ = "police_stations"

    station_id = Column(Integer, primary_key=True, index=True)
    station_name = Column(String)
    location = Column(String)
    contact_number = Column(String)

    officers = relationship("PoliceOfficer", back_populates="station")


class PoliceOfficer(Base):
    __tablename__ = "police_officers"

    officer_id = Column(Integer, primary_key=True, index=True)
    name = Column(String)
    email = Column(String)
    password = Column(String)
    rank = Column(String)
    contact = Column(String, nullable=True)  # ✅ ADD: Officer contact number
    location = Column(String, nullable=True)  # ✅ ADD: Officer location/jurisdiction

    station_id = Column(Integer, ForeignKey("police_stations.station_id"))

    station = relationship("PoliceStation", back_populates="officers")

    # ✅ IMPORTANT: must match FIR side
    firs = relationship("FIR", back_populates="officer")


class FIR(Base):
    __tablename__ = "firs"

    fir_id = Column(Integer, primary_key=True, index=True)
    officer_id = Column(Integer, ForeignKey("police_officers.officer_id"), nullable=True)

    incident_location = Column(String, nullable=True)
    crime_type = Column(String, nullable=True)
    description = Column(Text)  # ✅ Original complaint text
    generated_fir = Column(Text, nullable=True)  # ✅ ADD: Formal FIR generated by LLM
    date = Column(Date, nullable=True)
    status = Column(String, nullable=True)
    embedding = Column(Vector(384), nullable=True)
    created_at = Column(Date, nullable=True)  # ✅ ADD: When FIR was created

    # ✅ must match PoliceOfficer
    officer = relationship("PoliceOfficer", back_populates="firs")

    # ✅ must match Evidence
    evidence = relationship("Evidence", back_populates="fir")

    # ✅ must match AIAnalysis
    analysis = relationship("AIAnalysis", back_populates="fir", uselist=False)


class Evidence(Base):
    __tablename__ = "evidence"

    evidence_id = Column(Integer, primary_key=True, index=True)
    fir_id = Column(Integer, ForeignKey("firs.fir_id"))

    evidence_type = Column(String)
    file_path = Column(String)
    description = Column(Text)

    # ✅ must match FIR
    fir = relationship("FIR", back_populates="evidence")


class AIAnalysis(Base):
    __tablename__ = "ai_analysis"

    analysis_id = Column(Integer, primary_key=True, index=True)
    fir_id = Column(Integer, ForeignKey("firs.fir_id"))

    predicted_crime_category = Column(String)
    missing_information = Column(Text)
    confidence_score = Column(Float)
    suggestions = Column(Text)
    analysis_date = Column(Date)

    # ✅ must match FIR
    fir = relationship("FIR", back_populates="analysis")
    
    
    
class ChatHistory(Base):
    __tablename__ = "chat_history"

    chat_id = Column(Integer, primary_key=True, index=True)
    fir_id = Column(Integer)
    message = Column(Text)
    role = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    